### PR TITLE
screenshots of current state

### PR DESCRIPTION
**Pull request by ajirk**
Fixes #Add screenshots of the current state of app in readme file. #89

Changes: Added screenshots of current state.

Screenshots of the change: Screenshot (1)

### CODE REVIEW

**Comment by atm1504** [comment]
Make the pr into development branch instead of master.

**Comment by amangrobo** [comment]
make PR in development branch not master

**Comment by atm1504** [comment]
@ajirk do add images of the present state of app. Images added are very old.
Also make use of tables and rows to display around 3 images in a row.

**Review by chanmol1999 — CHANGES_REQUESTED** [review]
No need to change so many files

**Pull request closed without merging**
