### PR TITLE
Add word card

### PR DESCRIPTION
**Pull request by oindrilabhadra78**
Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issue" #IssueNumber]

Changes: [Add here what changes were made in this pull request and if possible provide links showcasing the changes.]

Screenshots of the change: [Add screenshots depicting the changes.]

### CODE REVIEW

**Comment by atm1504** [comment]
@oindrilabhadra78 add a screenshot of the card in comment. Thank you : )

**Comment by oindrilabhadra78** [comment]
Fixes #38

WordCardScreenshot

**Comment by atm1504** [comment]
@oindrilabhadra78 make the card like the one shown in the pic below. Text should appear over the background. We need only one textView not two. Make the required changes. 

Screenshot 2019-03-23 at 1 45 37 AM

**Comment by atm1504** [comment]
It would be better if you upload a screenshot : )

**Comment by oindrilabhadra78** [comment]
WordCard

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
