### PR TITLE
added A-Z alpohabets for dictionary

### PR DESCRIPTION
**Pull request by aparsh**
<string-array name="alphabets">
        <item>A</item>
        <item>B</item>
        <item>C</item>
        <item>D</item>
        <item>E</item>
        <item>F</item>
        <item>G</item>
        <item>H</item>
        <item>I</item>
        <item>J</item>
        <item>K</item>
        <item>L</item>
        <item>M</item>
        <item>N</item>
        <item>O</item>
        <item>P</item>
        <item>Q</item>
        <item>R</item>
        <item>S</item>
        <item>T</item>
        <item>U</item>
        <item>V</item>
        <item>W</item>
        <item>X</item>
        <item>Y</item>
        <item>Z</item>

    </string-array>

### CODE REVIEW

**Review by chanmol1999 — CHANGES_REQUESTED** [review]
Revert changes in misc. xml

**Comment by atm1504** [comment]
@Ashgo18 don't make pr over others pr, until you are asked for it

**Comment by atm1504** [comment]
@aparsh are you correcting the code or shall I take up @Ashgo18 pr's.

**Comment by aparsh** [comment]
I am correcting it...

**Pull request closed without merging**
